[env:stm32f103rc]
platform = ststm32
board = genericSTM32F103RC
framework = stm32cube

build_flags = 
    -ICore/Inc
    -IUser/ECW
    -IUser/SYSTEM/delay
    -IUser/SYSTEM/sys
    -IUser/SYSTEM/usart
    -DUSE_HAL_DRIVER
    -DSTM32F103xB

lib_deps =

monitor_speed = 115200
upload_protocol = stlink
debug_tool = stlink
